export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT_QUERY = "SET_PRODUCT_QUERY";
export const SET_ACTIVE_PRODUCT_DETAIL = "SET_ACTIVE_PRODUCT_DETAIL";
export const SET_ACTIVE_PRODUCT_DESCRIPTION = "SET_ACTIVE_PRODUCT_DESCRIPTION";
