export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const CLEAR_ACTIVE_PRODUCT = "CLEAR_ACTIVE_PRODUCT";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT_QUERY = "SET_PRODUCT_QUERY";
export const SET_ACTIVE_PRODUCT = "SET_ACTIVE_PRODUCT";
